# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js 16.x'

- script: |
    npm install -g @angular/cli
    npm install
    ng build
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  displayName: 'Archive dist files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/front-vinci-treasures'
    archiveType: zip
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: Container


